- type: job
  id: VDVRifleman
  name: job-name-vdv-rifleman
  description: job-description-vdv-rifleman
  playTimeTracker: JobVDVRifleman
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:FactionRequirement
      factionID: "PACT"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 77
  startingGear: VDVRiflemanGear
  alwaysUseSpawner: true
  icon: "JobIconPACTRifleman"
  requireAdminNotify: false
  supervisors: job-supervisors-rugov
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-private
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: VDVRiflemanGear
  equipment:
    id: VDVPDA
    ears: ClothingHeadsetAltRU
    jumpsuit: ClothingUniformJumpsuitCamoRUEMR
    head: ClothingHeadHatHelmetRUEMR
    outerClothing: ClothingOuterArmorPlateCarrierBlack
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackRucksackBlack
    neck: ClothingNeckIFFtapeWhite
  storage:
    back:
    - Crowbar
    - Gauze
    - SyringeSaline
    - BruteAutoInjector
    - Tourniquet
    - Zipties
