- type: job
  id: RURifleman
  name: Rifleman
  description: "Shoot Americans."
  playTimeTracker: JobRURifleman
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:FactionRequirement
      factionID: "PACT"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  startingGear: RURiflemanGear
  icon: "JobIconRU"
  joinNotifyCrew: false
  alwaysUseSpawner: true
  supervisors: job-supervisors-rugov
  canBeAntag: false
  access:
  - Cryogenics
  - Maintenance

- type: startingGear
  id: RURiflemanGear
  equipment:
    gloves: ClothingHandsMercGlovesCombat
    id: RUIDCard
    ears: ClothingHeadsetAltRU
    jumpsuit: ClothingUniformJumpsuitCamoRU
    head: ClothingHeadHatHelmetRU
    outerClothing: ClothingOuterArmorPlateCarrierBlack
    shoes: ClothingShoesBootsJack
    back: ClothingBackpackMerc
#  storage:
#    back:
#    - Crowbar
#    - Gauze
#    - SyringeSaline
#    - BruteAutoInjector
#    - Tourniquet