# - type: cargoProduct
#   id: ServiceJanitorialFreeport
#   icon:
#     sprite: Objects/Specific/Janitorial/janitorial.rsi
#     state: cleaner
#   product: CrateServiceJanitorialSupplies
#   cost: 560
#   category: cargoproduct-category-name-service
#   group: freeport

# - type: cargoProduct
#   id: ServiceLightsReplacementFreeport
#   icon:
#     sprite: Objects/Power/light_bulb.rsi
#     state: normal
#   product: CrateServiceReplacementLights
#   cost: 600
#   category: cargoproduct-category-name-service
#   group: freeport

# - type: cargoProduct
#   id: MousetrapBoxesFreeport
#   icon:
#     sprite: Objects/Devices/mousetrap.rsi
#     state: mousetrap
#   product: CrateMousetrapBoxes
#   cost: 500
#   category: cargoproduct-category-name-service
#   group: freeport

# - type: cargoProduct
#   id: ServiceBureaucracyFreeport
#   icon:
#     sprite: Objects/Misc/bureaucracy.rsi
#     state: pen
#   product: CrateServiceBureaucracy
#   cost: 1000
#   category: cargoproduct-category-name-service
#   group: freeport

# - type: cargoProduct
#   id: ServiceBooksFreeport
#   icon:
#     sprite: Objects/Misc/books.rsi
#     state: book_icon
#   product: CrateServiceBooks
#   cost: 1000
#   category: cargoproduct-category-name-service
#   group: freeport

