- type: job
  id: GliessianDockmaster
  name: job-name-gliess-dockmaster
  description: job-description-gliess-dockmaster
  playTimeTracker: JobGliessDockmaster
  startingGear: GliessDockmasterGear
  icon: "JobIconCaptain"
  supervisors: job-supervisors-lols
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 8000
  accessGroups:
  - GeneralAccess
  access:
  - GliessSheriff
  - GliessDockmaster
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ind-gliess-dockmaster
      - type: LanguageAdder
        addSpoken:
          - Tradeband
        addUnderstood:
          - Tradeband

- type: startingGear
  id: GliessDockmasterGear
  equipment:
    ears: ClothingHeadsetGrey
    shoes: ClothingShoesBootsLaceup
    jumpsuit: ClothingUniformJumpsuitCapFormal
    head: ClothingHeadHatCapcap
    belt: ClothingBeltSheathFilled
    id: GliessDockmasterPDA
    back: ClothingBackpackSatchelLeatherFilledDSM
