- type: job
  id: BoardSHI
  name: job-name-board
  description: job-description-board
  playTimeTracker: JobBoardSHI
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 14400
    - !type:CharacterSpeciesRequirement
      species:
        - Human
        - Reptilian
        - Moth
        - Arachnid
        - Felinid #makes no sense in lore considering that Felinids are created by SHI's competitors but MLG won't merge the change without this
    - !type:FactionRequirement
      factionID: "SHI"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - WheelchairBound
  weight: 50
  startingGear: BoardGear
  alwaysUseSpawner: true
  icon: "JobIconBoard"
  requireAdminNotify: true
  supervisors: job-supervisors-shi
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-shi-board
      - type: LanguageAdder
        addSpoken:
          - Kaishago
          - Tradeband
        addUnderstood:
          - Kaishago
          - Tradeband
  access:
  - Command
  - Maintenance
  - Shinohara
  - ShinoharaOfficer
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: BoardGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaSuit
    shoes: ClothingShoesBootsLaceup
    neck: ClothingNeckTieRed
    outerClothing: ClothingOuterShinoharaSuitJacket
    id: BoardPDA
    pocket1: TradePassport
    ears: ClothingHeadsetShinohara
    back: ClothingBackpackSHISatchel
