- type: job
  id: EmployeeSHI
  name: job-name-employee
  description: job-description-employee
  playTimeTracker: JobEmployeeSHI
  requirements:
    - !type:FactionRequirement
        factionID: "SHI"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - WheelchairBound
  weight: 25
  startingGear: EmployeeGear
  alwaysUseSpawner: true
  icon: "JobIconEmployee"
  requireAdminNotify: false
  supervisors: job-supervisors-shi
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-shi-employee
      - type: LanguageAdder
        addSpoken:
          - Kaishago
          - Tradeband
        addUnderstood:
          - Kaishago
          - Tradeband
  access:
  - Command
  - Maintenance
  - Shinohara
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: EmployeeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaLogistics
    shoes: ClothingShoesBootsJack
    belt: ClothingBeltUtilityEngineering
    id: EmployeePDA
    pocket1: TradePassport
    ears: ClothingHeadsetShinohara
