- type: department
  id: USMC
  description: department-USMC-description
  color: "#203564"
  weight: 72
  roles:
  - USMCRifleman
  - USMCAutomaticRifleman
  - USMCMedic
  - USMCRecon
  editorHidden: false

- type: department
  id: VDV
  description: department-VDV-description
  color: "#a02829"
  weight: 73
  roles:
  - VDVRifleman
  - VDVAutomaticRifleman
  - VDVMedic
  - VDVRecon
  editorHidden: false
