- type: job
  id: USRifleman
  name: Rifleman
  description: "Shoot Russians."
  playTimeTracker: JobUSRifleman
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:FactionRequirement
      factionID: "NATO"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  startingGear: USRiflemanGear
  icon: "JobIconUS"
  joinNotifyCrew: false
  alwaysUseSpawner: true
  supervisors: job-supervisors-usgov
  canBeAntag: false
  access:
  - External
  - Cryogenics
  - Maintenance

- type: startingGear
  id: USRiflemanGear
  equipment:
    gloves: ClothingHandsMercGlovesCombat
    id: USIDCard
    ears: ClothingHeadsetAltUS
    belt: ClothingBeltMilitaryWebbingUSFilledSTANAG
    jumpsuit: ClothingUniformJumpsuitCamoUS
    head: ClothingHeadHatHelmetUS
    outerClothing: ClothingOuterArmorPlateCarrierTan
    shoes: ClothingShoesBootsJack
    back: ClothingBackpackMerc
#  storage:
#    back:
#    - Crowbar
#    - Gauze
#    - SyringeSaline
#    - BruteAutoInjector
#    - Tourniquet
