- type: job
  id: USMCAutomaticRifleman
  name: job-name-usmc-automatic-rifleman
  description: job-description-usmc-automatic-rifleman
  playTimeTracker: JobUSMCAutomaticRifleman
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:FactionRequirement
      factionID: "NATO"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 76
  startingGear: USMCAutomaticRiflemanGear
  alwaysUseSpawner: true
  icon: "JobIconNATOSupport"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: BF-rank-corporal
      - type: HullrotFaction
        faction: USMC
      - type: LanguageAdder
        addSpoken:
          - American
        addUnderstood:
          - American
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOMaintenance
  - NATOSoldier
  - NATOArmory

- type: startingGear
  id: USMCAutomaticRiflemanGear
  equipment:
    id: USMCAutomaticRiflemanPDA
    ears: ClothingHeadsetAltUS
    belt: ClothingBeltMilitaryWebbingUSFilledSTANAG
    jumpsuit: ClothingUniformJumpsuitCamoUS
    head: ClothingHeadHatHelmetUSRiot
    eyes: ClothingEyesGogglesTan
    outerClothing: ClothingOuterArmorPlateCarrierTan
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackRucksackTan
    suitstorage: WeaponRifleUSM27IAR
  storage:
    back:
    - SupplyBoxAmmoUSFilled
    - Tourniquet
