- type: job
  id: WorkerOverbossNCWL
  name: job-name-ncwl-worker-overboss
  description: job-description-ncwl-worker-overboss
  playTimeTracker: JobEngineeringLeaderNCWL
  weight: 4
  startingGear: SupervisorNCWLGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconNCWLEngineeringLeader"
  supervisors: job-supervisors-ncwl-leaders
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-engi-leader
      - type: LanguageKnowledge
        speaks:
          - Dockta
          - TauCetiBasic
          - Tradeband
        understands:
          - Dockta
          - TauCetiBasic
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - NCWLGeneral
  - NCWLKommissar
  - NCWLJail
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: SupervisorNCWLGear
  equipment:
    shoes: ClothingShoesBootsSalvage
    jumpsuit: ClothingUniformJumpsuitNCWLArtificer
    id: NCWLEngineeringLeaderPDA
    outerClothing: ClothingOuterArmorNCWLEngi
    belt: ClothingBeltUtilityFilled
    pocket1: WeaponPistolHKUSP
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesColorYellow
    head: ClothingHeadHatBeretEngineering
    ears: ClothingHeadsetNCWL
    eyes: ClothingEyesHudSecurity
