- type: entity
  id: StandardCrescentStation #Main faction stations
  parent:
    - BaseStation
    - BaseStationCargo
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationShuttles
    - BaseStationAlertLevels
    - BaseStationSiliconLawCrescentStation
    - BaseStationSectorNews
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform

- type: entity
  id: StandardCrescentPOI #POI
  parent:
    - BaseStation
    - BaseStationShuttles
    - BaseStationCargo
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform

- type: entity
  id: FlagshipCrescentVessel #Flagship , gets spawning capabilities :) SPCR
  parent:
    - BaseStation
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationCargo
    - BaseCombatShipAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationDynamicFaxWarpHolopad
    - BaseStationSiliconLawCrescentShips
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform

- type: entity
  id: StandardCrescentVessel #Combat vessel
  parent:
    - BaseStation
    - BaseStationRecords
    - BaseStationCargo
    - BaseCombatShipAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationDynamicFaxWarpHolopad
    - BaseStationSiliconLawCrescentShips
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform


- type: entity
  id: StandardCrescentCivilianVessel #Civilian / unarmed vessel
  parent:
    - BaseStation
    - BaseStationRecords
    - BaseStationAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationDynamicFaxWarpHolopad
    - BaseStationCargo
    - BaseStationSiliconLawCrescentShips
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform
    - type: ShipRenameHolopad
    - type: StationRenameWarps

- type: entity
  id: StandardCrescentExpeditionVessel #Expeds
  parent:
    - BaseStation
    - BaseStationRecords
    - BaseStationAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationDynamicFaxWarpHolopad
    - BaseStationCargo
    - BaseStationSiliconLawCrescentShips
    - BaseStationExpeditions
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform

- type: entity
  id: StandardCrescentExpeditionVesselCombat #Expeds
  parent:
    - BaseStation
    - BaseStationRecords
    - BaseCombatShipAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationDynamicFaxWarpHolopad
    - BaseStationCargo
    - BaseStationSiliconLawCrescentShips
    - BaseStationExpeditions
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform

- type: entity
  id: BaseStationSiliconLawCrescentStation
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: NTDefault

- type: entity
  id: BaseStationSiliconLawCrescentShips
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Corporate

- type: entity
  id: BaseStationDynamicFaxWarpHolopad
  abstract: true
  components:
    - type: StationRenameFaxes
    - type: StationRenameWarps
    - type: ShipRenameHolopad

# Sector-wide news access, should be on stations with comms (radio station, telecomms)
- type: entity
  id: BaseStationSectorNews
  abstract: true
  components:
    - type: SectorNews

- type: entity
  id: BaseCombatShipAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: combatShipAlerts
